name: Auto Update README

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.md"
      - ".github/scripts/update_readme.py"
      - ".github/workflows/auto-readme.yml"
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * 1"  # Every Monday 06:00 UTC (optional)

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Install Python dependencies
        run: |
          pip install matplotlib seaborn pandas

      - name: Regenerate README
        run: |
          python .github/scripts/update_readme.py

      - name: Commit changes (if any)
        run: |
          if git diff --quiet README.md; then
            echo "No README changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-update README [skip ci]"
            git push
          fi
